const express= require('express')
const loginRegister = require('./loginRegisterRoute')
const dynamicTable = require('./dynamicTableRoute')
const kukuCube =require('./KukuCubeRoute')
const ticTacToe = require('./ticTacToeRoute')
const sorting = require('./sortingRoute')
const eventsJavascript = require('./eventJavascriptRoute')
const paginationOrderBy = require('./paginationOrderByRoute')
const attendanceReport = require('./attendenceReportRoute')
const result = require('./resultRoute')

const search = require('./searchRoute')
const delimeterSearch = require('./delimeterSearchRoute')
const stateCity = require('./stateCityRoute')
const cities = require('./cityRoute')
const ajaxJobAppForm = require('./jobAppFormRoute')
const timeZoneConvertor = require('./timeZoneConvertor')
const ajaxPaginationPosts = require('./ajaxFetchApiPagination')
const forgetPassword = require('./forgetPasswordRoute')
const cssPractical1 = require('./cssPractical1')
const cssPractical2 = require('./cssPractical2')
const cssPractical3 = require('../controller/cssPractical3/cssPractical3')


const router = express.Router()

router.use('/',loginRegister)
router.use('/',dynamicTable)
router.use('/',kukuCube)
router.use('/',ticTacToe)
router.use('/',sorting)
router.use('/',eventsJavascript)
router.use('/',paginationOrderBy)
router.use('/',attendanceReport)
router.use('/',result)

router.use('/',search)
router.use('/',delimeterSearch)
router.use('/',stateCity)
router.use('/',cities)
router.use('/',ajaxJobAppForm)
router.use('/',timeZoneConvertor)
router.use('/',ajaxPaginationPosts)
router.use('/',forgetPassword)
router.use('/',cssPractical1)
router.use('/',cssPractical2)
router.use('/',cssPractical3)

module.exports = router
